routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('bombas.index');
});*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/verificar', 'BombaController@Carga')->name('verificar');

Route::get('/timbrado', 'BombaController@timbrado')->name('timbrado');

//Route::get('/lista', 'BombaController@obtenerListadoDeArchivos')->name('lista');

Route::get('/xml/{id}', 'BombaController@downloadXML')->name('xml');

Route::post('/borrar/{id}', 'BombaController@destroy')->name('borrar');

Route::get('/carga', function () {
    return view('carga');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('/', 'BombaController');





Route::resource('orgs', 'orgsController');

Route::resource('facts', 'factsController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pensiones</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
            <!-- Header Navbar -->
            <nav>
                <div class="nav-wrapper black">
                    <a href="{{url('/bombas')}}" class="brand-logo">Pensiones</a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a href="{{url('/bombas')}}">Timbrado</a></li>
                        <li><a href="{{url('/carga')}}">Carga excel</a></li>
                    </ul>
                </div>
            </nav>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav>
        <div class="nav-wrapper black">
            <a href="{{url('/')}}" class="brand-logo">Pensiones</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{{url('/')}}">Timbrado</a></li>
                <li><a href="{{url('bombas')}}">Carga excel</a></li>
                <li> <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('bombas.create') }}">Add New</a></li>
            </ul>
        </div>
    </nav>
<body>

<div class="row">

    <div class="col s12 m12">
        <span class="blue-text text-darken-2" style="font-size: 12px;">
            <table class="responsive-table centered">
        <thead class="text-black ">
          <tr>
              <th>No Est</th>
        <th>Num Pen</th>
        <th>Rs</th>
        <th>Rfc</th>
        <th>Clave Sat</th>
        <th>Clave Unidad</th>
        <th>Descripcion</th>
        <th>Total</th>
        <th>Uso Cfdi</th>
        <th>Forma Pago</th>
        <th>Email User</th>
        <th>Email Gerente</th>
        <th>Tmbrada</th>
                <th colspan="3">Action</th>
          </tr>
        </thead>
        @foreach($bombas as $bomba)
                    <tbody>
          <tr>

           <td>{{ $bomba->no_est }}</td>
            <td>{{ $bomba->num_pen }}</td>
            <td>{{ $bomba->rs }}</td>
            <td>{{ $bomba->rfc }}</td>
            <td>{{ $bomba->clave_sat }}</td>
            <td>{{ $bomba->clave_unidad }}</td>
            <td>{{ $bomba->descripcion }}</td>
            <td>{{ $bomba->total }}</td>
            <td>{{ $bomba->uso_cfdi }}</td>
            <td>{{ $bomba->forma_pago }}</td>
            <td>{{ $bomba->email_user }}</td>
            <td>{{ $bomba->email_gerente }}</td>
            <td>{{ $bomba->tmbrada }}</td>

          </tr>
    @endforeach
        </tbody>
      </table>
        </span>
    </div>


</div>

</body>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{{ route('users.index') }}"><i class="fa fa-edit"></i><span>Users</span></a>
</li>

<li class="{{ Request::is('bombas*') ? 'active' : '' }}">
    <a href="{{ route('bombas.index') }}"><i class="fa fa-edit"></i><span>Bombas</span></a>
</li>

<li class="{{ Request::is('orgs*') ? 'active' : '' }}">
    <a href="{{ route('orgs.index') }}"><i class="fa fa-edit"></i><span>Orgs</span></a>
</li>

<li class="{{ Request::is('facts*') ? 'active' : '' }}">
    <a href="{{ route('facts.index') }}"><i class="fa fa-edit"></i><span>Facts</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>